name: Github actions demo
on: push
jobs:
  action-demo: 
     runs-on: ubuntu-latest
     steps:
       - name: chekout the code
         uses: actions/checkout@v4
       - name: print index.html
         run: cat index.html
    
